### ISSUE TITLE
could not find file webpack-aspnet5\build\webpack.assets.json

### ISSUE THREAD

**Issue by mycall** [scottaddie/webpack-aspnet5#1]
What suppose to be in the build directory?  Only web.config is there now.

**Comment by scottaddie** [comment]
The `build` folder is generated by the Webpack build and should contain:
1. `app.<insert_hash_here>.js`
2. `favicon.ico`
3. `vendor.<insert_hash_here>.js`
4. `webpack.assets.json`

Here's a screenshot of what I see in VS 2015 Update 1:

![build_folder](https://cloud.githubusercontent.com/assets/10702007/12603504/ec89e69c-c478-11e5-84d3-387e916c5538.png)

Are you seeing an error message?

**Comment by mycall** [comment]
I just rechecked and it things are working as you intended now.  Thanks for the cool ideas!
